### ISSUE TITLE
changing the number of replicas causes a rolling restart of all the regionservers

### ISSUE THREAD

**Issue by tsuna** [timoha/hbase-k8s-operator#23]
it shouldn't restart anything just because we add a regionserver

**Comment by timoha** [comment]
Provide more info. Which k8s versions, did you change config map, etc.

**Comment by pidren** [comment]
Hey there,

There was previous attempts to fix this issue:
https://github.com/timoha/hbase-k8s-operator/pull/15
https://github.com/timoha/hbase-k8s-operator/pull/10
https://github.com/timoha/hbase-k8s-operator/pull/7

I'm working on verifying we're still being hit by this bug.

**Comment by mihkulemin** [comment]
#25 is another attempt to fix the issue
